Package Update & Code Refactors
ArunPrakashG/wordpress_client pull request #17
Opened 2023-05-22 18:07 UTC by ArunPrakashG

As a part of the next release, i am planning on refactoring the existing codebase and update the repo packages. This PR contains some refactors and package updates.

@mikhaelpurba , i have done some changes to the "json" property on all base responses. i have separated it into a different abstract class and the property has been renamed to "self"
i think it would provide a clearer picture to what exactly the property does.

In future, we could return just this property from the response method in case parsing of the entire JSON fails.

2023-05-22 18:41 UTC, mikhaelpurba requested changes
tested it, working just fine on my app with small modification.

maybe consider deprecating the 'json' keyword before removing it, or make it a getter? it's an incompatible change, after all...

2023-05-22 19:09 UTC, mikhaelpurba approved these changes

2023-05-25 18:08 UTC, merged

2023-05-25 18:10 UTC, ArunPrakashG commented
Thank you @mikhaelpurba

2023-05-25 18:19 UTC, ArunPrakashG commented
A new release has been published!
Version 7.0.0
https://pub.dev/packages/wordpress_client

cc: @mikhaelpurba @tehseengds